import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Toaster } from "sonner";
import localFont from "next/font/local";
import Providers from "@/lib/providers/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const chillax = localFont({
  src: "../../public/fonts/Chillax.woff2",
  variable: "--font-chillax",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={chillax.className}>
          <AppRouterCacheProvider>
            <Toaster position="top-right" />
            {children}
          </AppRouterCacheProvider>
        </body>
      </Providers>
    </html>
  );
}
